GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDM3Mzk4ODUsImV4cCI6MTc0MzczOTkwMCwiYXVkIjoiNjdlZjQ5NmNkZThmYzJmNjdhOGY3NDdjIiwiaXNzIjoibm9kZV9hdXRoIn0.kC5MKu4ly9qrHS1A7HqgWKIN8Cth-MUix6Zxa3A-VDA

###Login route
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "user9@user.com",
    "password": "password"
}

###Register route
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "user9@user.com",
    "password": "password"
}

###Refresh token route
POST http://localhost:3000/api/auth/refresh-token

###Logout route
DELETE http://localhost:3000/api/auth/logout