GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDM3NDMwMzksImV4cCI6MTc0Mzc0MzkzOSwiYXVkIjoiNjdlZjQ5NmNkZThmYzJmNjdhOGY3NDdjIiwiaXNzIjoibm9kZV9hdXRoIn0.nt6S3uLc2fnYmJ3VYG80DuhAhcEZ-vQv_WJsSwY0fmQ

###Login route
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "user9@user.com",
    "password": "password"
}

###Register route
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "email": "user10@user.com",
    "password": "password"
}

###Refresh token route
POST http://localhost:3000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDM4NDQ3NjksImV4cCI6MTc3NTQwMjM2OSwiYXVkIjoiNjdlZjQ5NmNkZThmYzJmNjdhOGY3NDdjIiwiaXNzIjoibm9kZV9hdXRoIn0.aYsxj_qeIaBF0LPJmF4uFAcHzl9rVKsP3IHKAAcD-8A"
}

###Logout route
DELETE http://localhost:3000/api/auth/logout
content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3NDM4NjgwMTYsImV4cCI6MTc3NTQyNTYxNiwiYXVkIjoiNjdlZjQ5NmNkZThmYzJmNjdhOGY3NDdjIiwiaXNzIjoibm9kZV9hdXRoIn0.DfJrYsCGdhsSD1yOHFUdbKtAfph15nuP1RqwRRSyxno"
}